apiVersion: v1
kind: ServiceAccount
metadata:
  name: lakehouse-service-account
  annotations: {}
imagePullSecrets: []

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iomete-lakehouse-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - events
      - persistentvolumeclaims
      - pods/log
      - namespaces
      - endpoints
  - verbs:
      - get
    apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
  - verbs:
      - '*'
    apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - resourcequotas
  - verbs:
      - create
      - get
      - update
      - delete
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - create
      - get
      - update
      - delete
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
  - verbs:
      - '*'
    apiGroups:
      - sparkoperator.k8s.io
    resources:
      - '*'
      - sparkapplications
      - sparkapplications/status
      - scheduledsparkapplications
      - scheduledsparkapplications/status
  - verbs:
      - '*'
    apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - '*'
  - verbs:
      - delete
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - events.k8s.io
    resources:
      - events
  - verbs:
      - create
      - get
      - update
      - delete
    apiGroups:
      - ""
    resources:
      - services
      - configmaps
      - secrets
      - events
      - nodes
      - resourcequotas
  - verbs:
      - create
      - get
      - delete
    apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
  - verbs:
      - create
      - update
      - patch
    apiGroups:
      - ""
    resources:
      - events
  - verbs:
      - '*'
    apiGroups:
      - scheduling.incubator.k8s.io
      - scheduling.sigs.dev
      - scheduling.volcano.sh
    resources:
      - podgroups
  - verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases


---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iomete-lakehouse-role-binding
roleRef:
  kind: Role
  name: iomete-lakehouse-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: lakehouse-service-account
