apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: spark-operator-{{namespace}}
webhooks:
  - name: webhook.sparkoperator.k8s.io
    clientConfig:
      service:
        namespace: {{namespace}}
        name: spark-operator-webhook
        path: /mutate--v1-pod
        port: 443
      caBundle: {{caBundle}}
    rules:
      - operations:
          - CREATE
        apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - pods
        scope: "Namespaced"
    failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector:
      matchLabels:
        iomete.com/managed: "true"
    objectSelector: {}
    sideEffects: NoneOnDryRun
    timeoutSeconds: 30
    admissionReviewVersions:
      - v1
    reinvocationPolicy: Never
